#!/usr/bin/python3

import vectors
import sys
import os

preambule = "// This source file has been generated by generate.py->"

if __name__ == "__main__":
    gen_path = sys.argv[1] if len(sys.argv) > 1 else 'src/generated/'
    if not os.path.exists(gen_path): os.mkdir(gen_path)

    with open(gen_path + "vectors.generated.inline.h", "w") as out:
        out.write(preambule + "vectors.py\n\n")
        out.write(vectors.generate())